#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 黒龍の塔
** 7
   太陽とともに月もその姿を消した。だがその魔力は，夜の続くこの世界にいまだ残っている。かつて新月と呼ばれた日，そして月の魔力が最も弱まる日，それが今では真月と呼ばれている。人のもつ憎しみ，恨み，つらみ，嫉妬，嘆き，光なきものが最も強まる時でもある。

   白装束の者に案内され都の下水道から出ると，ミトはロジャ選りすぐりの戦士達とともに，北方にある月の塔を目指した。その間，都を行き来する者を狙う盗賊に幾度も襲われた。黒龍に会う前であれば何なく打ち倒せた敵だった。だがその力のほとんどは失われている。苦戦が続くなかで戦士は一人，また一人と倒れていき，やがて月の塔に着く頃にはミト一人だけになっていた。

   月の塔はどの街からも遠く離れ，訪れる者もない。閑散とした塔の内部は，かつての戦いの跡が朽ちた鎧と風化した骨に残されているのみだ。塔の暗闇でミトは真月の日を待ち，その日は訪れた。袋の中の暗銀が低くうなるように震え，漆黒のなかでより暗き台が部屋の中央に浮かんできたのだ。

   ミトは台の上に暗銀の板を乗せると，鎚で打った。板とともにその身は激しく震え，皮膚が裂けた。それでも打ちつづけた。板は返り血を浴びながらやがてその姿を真円に変えていく。

   ついにそれは，全ての光を飲み込む，黒き真円の盾となった。これに触れれば，もはや人として生きることはかなわぬだろう。しばしの逡巡ののち，ミトは盾の面に触れた。

   全身の血，肉，骨が全て粉々になるほどの衝撃があった。盾は手の平に吸いつき離れず，その痛みにミトはのたうちまわった。盾は手の肉を食いやぶり，指や骨をえぐりながら，手の甲に再び現れ，そこに留まった。

  <br>

  -- stab --

  <br>
  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]


