#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* モンスター設定
** 裂掌獣ザエル
   - 湿林の主とも称される，発達した前腕に鋭い爪をもつモンスター。上半身は荒いウロコに覆われているが，下半身および尻尾には柔らかい毛が生えている。狼に似た頭部から肉食であることがうかがえる。
   - 最大の特徴は，手の平を叩きつける際に放たれる爆発。その爆炎は前方の広い範囲に及び，獲物を一瞬にして葬る。これは体内の物質を爪先から噴射し，その化学反応によってひきおこすと考えられている。この攻撃は，危険が迫ったり，大物を仕留める必要が生じたときに奥の手として用いられる。その爆風を防ぐため，腕には特に硬いウロコが密集している。
   - 大きな獲物の少ない湿林では小動物や昆虫を主に食す。樹の中に済む幼虫や，高所にある動物の巣を得るため，ザエルの生息地域では切り裂かれた樹が多く見つかる。この地域の昆虫から得られる物質が，先の爆炎に利用されているようだ。
   - 一見すると森を破壊しているようだが，獲物は古木にひそんでいることが多いため，結果的に間伐となる。これにより深い森に光が差し，新たな木が生長しやすくなる。
   - モデルはモンスターハンターに登場するジンオウガ。能力のモデルはミイデラゴミムシ。
** 雷掌獣ザエル・ウロ
   - 湿原に生息する，ザエルの近縁種と推察されるモンスター。ザエルと異なり，ぬめりのあるウロコで覆われている。
   - 腕を叩きつけた際に放たれるのは水をつたう雷撃。その範囲は水面の広範囲に及ぶため，ザエルの爆炎よりもはるかに回避しづらい。この攻撃は，腕の筋細胞で発生させた電気エネルギーによってなされると考えられている。この能力と引き換えに，繊細な仕組みをもつ腕が弱点となる。
   - 水中に住む魚や，それを狙ってやってきた鳥などを食べる。草がより多く生えている草原などに行けば草食獣などが得られやすいはずだが，乾季に訪れる個体を除き積極的に進出することはない。
   - 能力のモデルはデンキウナギ。
** 城蝸牛プテリオン
   - 砂漠に生息する超巨大巻貝。その白く輝く殻には有機物が結晶化し，希少価値の高い宝石となっている。その宝石が持つ価値，およびあまりに巨大かつ狩猟した際に生じる環境への影響が予測できないため，ギルドの討伐対象となることはない。
   - ふだんは身体を砂中に隠し，ゆっくり進みながら砂の中にある有機物を摂取する。
   - プテリオンの殻には鳥などが生息し，他の砂漠とは異なる独自の環境が営まれる。
** 泥盤獣タルポラ
   - 湿原に生息する，背中に厚い泥の層を積んだモンスター。ふだんはその巨体を泥の中に沈め，水面近くの魚や，水を飲みにやってきた草食獣などを丸のみにする。
   - 危険が迫ると，敵に尻を向け，防御態勢をとる。それでも相手がひき返さない場合は，尻側に突進し，相手を押し潰す。
   - その背中は平たく，寄生虫をとりのぞくために日光浴をするたび，泥の層が固く積み重なってゆく。
   - モデルはウォンバット。
** 岩盤獣タルポラ・アプ
   - 火山湖付近に生息する，タルポラの近縁種。全身は固い金属のウロコで覆われ，特に背中はひびわれた鉄板のようになっている。原種にくらべ活動は鈍いが，ひとたびこの鉄板で攻撃されれば相手が受けるダメージは原種の比ではないだろう。
   - この付近には硫黄を含む有毒な汚泥があり，タルポラ・アプは体内に特殊な細菌を持つことでこの地形に適応したと考えられる。
   - モデルはスケーリーフット。
** 天巾アールケナン
   - 針山付近を回遊する超巨大モンスター。見た目は空全体を覆うほどの布のようであり，風に流されながら移動する。
   - その身体からはいくつものヒモのような管が垂れ下がっており，これに触れた生物をからめとって養分を吸収する。この管には強力な神経毒が含まれており，いったん獲物の皮膚に触れると即座に身体を麻痺させてしまう。
   - この生物はひとつの巨大な個体ではなく，いくつもの小型の個体が集まってできた群体であると考えられている。
   - 大きくなりすぎた群体は，風に任せ自然に破れ，別の群体となる。
   - てんきん，と読む。
   - モデルはカツオノエボシ。
** 黒鼈甲ルンマ
   - アールケナンを主食とする，空を飛ぶ亀。その甲羅は非常に軽く，黒い。これは変温動物である自身が上空で太陽の熱を吸収しやすいようにするためだと考えられている。
   - 飛び立つのは苦手で，強い風を必要とする。そのかわり産卵をのぞき地上に降りることはまれで，睡眠も飛びながらとる。
   - くろべっこう，と読む。
** 毛鞠獣テンバイ
   - 針山に生息する，全身を毛に覆われた，長い口吻をもつモンスター。舌を伸ばし，茨の茎付近にある芽を食べる。見た目はアリクイに似ている。
   - 針山の枝を飛び回る様子が，鞠が跳ねるように見える。
   - 後ろ足が固いヒヅメのようになっており，トゲが刺さるのを防ぐ。これは敵に対し高所から攻撃する武器にもなる。
   - モデルはベローシファカ。
** 虚凧ディディンナ
   - 湿林に生息する陸生のイカ。大きく発達した2本の触腕で，枝を自在に移動する。極めて高度な擬態能力を持つことから，虚凧 (うつろだこ) の異名を持つ。
   - 興奮状態になると，眼球および触腕が赤く尾を引く。これは本体と触腕を攪乱させ，敵に的を絞らせないための戦術と考えられる。
   - 吐き出される墨は粘度が高く，接触した相手にまとわりつき動きを封じてしまう。
   - モデルはフューチャーイズワイルドに登場するスクイボン。
** 土蜘蛛アクタニス
   - 平原全体を縄張りとする超巨大モンスター。その正体は何らかの原因で虚凧ディディンナが変異した個体と考えられている。
   - 地を這うワーム状の超巨大モンスターに見えるものはアクタニスの触腕で，本体は地中深くに隠れている。正確な大きさは測定できていないものの，触腕を含めた全体の大きさは「地平線まで見渡す限り」と報告されている。
   - 草食獣だけでなく，雷掌獣ザエル・ウロなどの強力な大型モンスターでさえも獲物となる。アクタニスによって平原の生態系が崩壊の危機にさらされているとして，ギルド本部はこの生物の討伐命令を下した。
   - その後の調査から，この生物は異形生物Aに分類されることとなる。
   - モデルはモンスターハンターに登場するオストガロア。
   - 名前の由来は「『芥にす (あくたにする，灰燼に帰す)』」から。
** 紫針竜ブレミオン
   - 発達した針のような尾を持つ，ワイバーン型のモンスター。大きな翼とは対照的に，後ろ足はほぼ退化しており，攻撃に使用することはできない。特定の縄張りは持たず，上空を飛ぶ様子が観察されることが多い。
   - 巨体にも関わらず動きは機敏で，硬い尾を使った攻撃を主体とする。最大の大技は，高高度まで上昇してからの尾による急降下攻撃。直撃すれば重症では済まないが，仮に避けられたとしても，突き刺さった地面が割れ，その破片と衝撃波が相手を襲う。ただし深く突き刺さった尾を抜くのは容易でなく，大きな隙にもなる。
   - その後の調査から，この生物は異形生物Bに分類されることとなる。
   - モデルはスズメバチ。急降下攻撃のモデルは機動戦士ガンダム・鉄血のオルフェンズに登場する兵器，ダインスレイヴ。
** 暴掌獣ブランザエル
   - 何らかの原因で，裂掌獣ザエルが変異したと考えられるモンスター。異常に発達した硬質の爪と，全身を覆う美しい白毛が特徴。
   - ザエル種は本来，その腕が持つ特性のため，腕による連続攻撃が不得意であった。だがこの個体はその特性を失ったことで，かえって他の種ではなし得なかった俊敏な攻撃を獲得した。
   - その攻撃速度は肉眼で捉えることが困難なほど。ゆえに，いったん爪につかまれば即座に八つ裂きにされてしまうだろう。
   - あまりの運動速度に知能が追いついていないらしく，後方に隙が多い。
   - その後の調査から，この生物は異形生物Cに分類されることとなる。
** 水葡萄ピアトーン
   - ナマコに似た生物の群体で，火山湖と思われていたものの正体。
   - 各個体は透明度が高く，水分を多く含むが，その成分は強力な酸性を示す。
   - 水に擬態し，やってきた生物をひきずりこむ。
   - この地域は季節によって川の水量が異なるため，水を求めてゆっくり移動する。
   - モデルはナマコの一種，グミ。
** 翅尾獣トゥントゥク
   - 覇鱗樹エストゥバを住処とするモンスター。平たい尾をプロペラのように使い，弾力に富む葉のうえを自在に動きまわる。
   - 知能が高く，エストゥバの種子を食べ体力回復をはかったり，またそれを投げて攻撃したり，さらにはエストゥバの花粉をまとって自己強化をはかったりするなど，からめ手での戦闘を得意とする。
   - 最大の特徴でもあるその尾は硬いが弱点でもあり，割れてしまうと大幅に弱体化する。
   - しびじゅう，と読む。
   - モデルはモミジの種子。
** 覇鱗樹エストゥバ
   - 地底大空洞に偏在する大樹。一見すると樹のようだが，そのウロコのような樹皮は脈打ち，花粉を放出する器官はエラのようでもある。また種子の中身を粘り気のある液体が満たしているなど，動物のような多くの特徴をもつ。
   - 翅尾獣トゥントゥクはエストゥバを住処とするかわり，花粉を媒介する共生関係にあると考えられている。
** 狡舞鳥グリュンプリド
   - 特定の縄張りを持たず，獲物を求めて各地に出没する鳥型のモンスター。身体の横に退化した翼をもち，発達した足で移動する。
   - 極めて高い知能を持ち，敵の位置や視野，さらには攻撃範囲や硬直時間まで把握し，攻撃をたくみにかわしながら舞うように戦う。常に嘴をカチカチ鳴らしていることから，大きな目だけでなく，音の反射も空間情報の取得に利用していると考えられている。その反面，これらの器官を維持するために莫大なエネルギーを必要とするため，常に食事をしなければならないという欠点も抱えている。
   - 正攻法での討伐は困難であると判断され，その旺盛な食欲を活かし，溶血剤入りのエサを食べさせる作戦がとられることとなる。
   - モデルはモンスターハンターに登場するイビルジョー。見た目のモデルはディアトリマなどの恐鳥類。
** 藍穿花シャクルワリム
   - 湿原から雪山付近にかけてのツンドラ地帯に生える巨大な植物。夜には青白く光る様子が美しい。葉のしげる巨木のようにみえるが，青白いものは葉ではなく小さな花である。
   - その花粉には動物に対する強い幻覚作用があり，吸い込んだ者を本体にひきよせる効果をもつ。シャクルワリムの周辺には生育の過程でできた大きな穴が空いているため，おびきよせられた動物は落下してしまう。
   - 穴の中は鋭く尖った根がイバラのようにはりめぐらされている。落下した動物はもがくほど身体につきささり，したたり落ちた血や脂が土を通して吸収される。こうしたシャクルワリムの捕食能力は，養分の少ないツンドラ地帯に適応するために獲得されたものだと考えられている。
** 蝕霧ディエボラン
   - 氷河が形成した谷に出現する，肉食性のバクテリアを含む霧。
   - この霧を吸引すると，粘膜をとおしてバクテリアが体内に入り込む。バクテリアは血管を傷つけながら増殖し，激しい炎症をひきおこす。
   - モデルはフィエステリア。
** 苔豚モムル
   - 蝕霧ディエボランが発生する地域に生息する，丸々と太った豚。谷に生えるキノコを主食とする。その肉質はやわらかく，美味で栄養価も高い。
   - 驚異的な肺活量をもち，数時間おきに谷から出て呼吸する。これによりバクテリアの侵入を防ぎ，蝕霧に守られた安全な生活を送ることができる。
   - 動きは鈍重。蝕霧という特殊な環境で酸素を節約するためだと考えられる。
   - モデルはモンスターハンターに登場するモス。
** 雪灯籠キューチェク
   - 雪原に生息するカイメンに似た生物。ふだんは雪中に姿を隠しているが，その身体は伸縮性に富み，近づいた獲物を丸のみにする。
   - 幼生は軽い毛に包まれており，空気中を浮遊しながら移動できる。
   - 幼生はある程度の距離までは成体と極細の毛でつながっている。これはセンサーとしての役割ももっており，獲物が接近すると空気の変化を敏感に感じ取って縮む性質をもつ。すると好奇心から獲物は幼生を追い，まんまと成体におびきよせられてしまう。こうした好奇心をもつ生物は大抵高い知能を持っているため，キューチェクにとっては栄養豊富な餌となる。
   - モデルはフナクイムシ。
** 虹旋蝶ネフレブリエ
   - 地底洞窟に生息する巨大な蝶。腹部から糸を放出して巣を作ったり，胸部から音を出したりするなど，通常の蝶とは異なる特徴をもつ。
   - 敵が接近すると，複数の個体ですりばち状の巣を作り，洞窟内の石片と共振する特殊な音波を発する。石片は共振でいったん跳ねあがると，糸の反発力もあいまって巣の中を超高速で飛びかい，敵をずたずたにする。
   - モデルはベターマンに登場するベターマン・ネブラ。

   Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

   [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]

 
