#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* モンスター設定
** 裂掌獣ザエル
   - 湿林の主とも称される，発達した前腕に鋭い爪をもつモンスター。上半身は荒いウロコに覆われているが，下半身および尻尾には柔らかい毛が生えている。狼に似た頭部から肉食であることがうかがえる。
   - 最大の特徴は，手の平を叩きつける際に放たれる爆発。その爆炎は前方の広い範囲に及び，獲物を一瞬にして葬る。これは体内の物質を爪先から噴射し，その化学反応によってひきおこすと考えられている。この攻撃は，危険が迫ったり，大物を仕留める必要が生じたときに奥の手として用いられる。
   - 獲物の数が限られる湿林では昆虫を主に食す。樹の中に済む幼虫を得るため，ザエルの生息地域では切り裂かれた樹が多く見つかる。この昆虫から得られる物質が先の爆炎に利用されているようだ。
   - 一見すると森林を破壊しているようだが，幼虫は古木にひそんでいることが多いため，古い木が適度に間伐されることで深い森に光が差し，新たな木が生長しやすくなる。
** 雷掌獣ザエル・ウロ
   - 湿原に生息する，ザエルの近縁種と推察されるモンスター。ザエルと異なり，ぬめりのあるウロコで覆われている。
   - 腕を叩きつけた際に放たれるのは水をつたう雷撃。その範囲は水面の広範囲に及ぶため，ザエルの爆炎よりもはるかに回避しづらい。この攻撃は，腕の筋細胞で発生させた電気エネルギーによってなされると考えられている。
   - 水中に住む魚や，それを狙ってやってきた鳥などを食べる。草がより多く生えている草原などに行けば草食獣などが得られやすいはずだが，乾季に訪れる個体を除き積極的に進出することはない。
** 城蝸牛プテリオン
   - 砂漠に生息する超巨大カタツムリ。その白く輝く殻には有機物が結晶化し，希少価値の高い宝石となっている。その宝石が持つ価値，およびあまりに巨大かつ狩猟した際に生じる環境への影響が予測できないため，ギルドの討伐対象となることはない。
   - ふだんは身体を砂中に隠し，ゆっくり進みながら砂の中にある有機物を摂取する。
   - プテリオンの殻には鳥などが生息し，他の砂漠とは異なる独自の環境が営まれる。
** 泥盤獣タルポラ
   - 湿原に生息する，背中に厚い泥の層を積んだモンスター。ふだんはその巨体を泥の中に沈め，水を飲みにやってきた草食獣などを丸のみにする。
   - 危険が迫ると，敵に尻を向け，防御態勢をとる。それでも相手がひき返さない場合は，尻側に突進し，相手を押し潰す。
   - その背中は平たく，寄生虫をとりのぞくために日光浴をするたび，泥の層が固く積み重なってゆく。
** 岩盤獣タルポラ・アプ
   - 火山湖付近に生息する，タルポラの近縁種。全身は固い金属のウロコで覆われ，特に背中はひびわれた鉄板のようになっている。原種にくらべ活動は鈍いが，ひとたびこの鉄板で攻撃されれば相手が受けるダメージは原種の比ではないだろう。
   - この付近には硫黄を含む有毒な汚泥があり，タルポラ・アプは体内に特殊な細菌を持つことでこの地形に適応したと考えられる。
